### ISSUE TITLE
Drop event listener

### ISSUE THREAD

**Issue by Gnzlt** [iPaulPro/Android-ItemTouchHelper-Demo#11]
As you said at your Medium post, we’re changing the position of the item every time the view is shifted to a new index, and not at the end of a “drop” event.

So, would it be possible to add a listener or to be notified at the end of a drop event in order to make changes to the layout or to store those changes in a DB?

**Comment by kyleparker** [comment]
Running into the same question/problem - after swiping/dismissing an item in the list, I need to perform actions in my top-level activity/fragment to update the DB, show the snackbar, etc. Looking forward to the next post and hopefully some insight on how to accomplish this! 

Thank you for taking the time to write these posts - they are very helpful!

**Comment by MFlisar** [comment]
Saving changes on every move is damn slow. But the docs of the `ItemTouchHelper.Callback` says, that it will be called if the drag is finished. So just do following (take notice of the `mFrom` and `mTo` and of the added function `onDrop`, you have to add this to the `ItemTouchHelperAdapter` interface):

Extend the `SimpleItemTouchHelperCallback` like following:

```
public class SimpleItemTouchHelperCallback extends ItemTouchHelper.Callback {

private Integer mFrom = null;
private Integer mTo = null;

....

@Override
public boolean onMove(RecyclerView recyclerView, RecyclerView.ViewHolder source, RecyclerView.ViewHolder target) {
    if (source.getItemViewType() != target.getItemViewType()) {
        return false;
    }

    // remember FIRST from position
    if (mFrom == null)
        mFrom = source.getAdapterPosition();
    mTo = target.getAdapterPosition();

    // Notify the adapter of the move
    mAdapter.onItemMove(source.getAdapterPosition(), target.getAdapterPosition());
    return true;
}

@Override
public void clearView(RecyclerView recyclerView, RecyclerView.ViewHolder viewHolder) {
    super.clearView(recyclerView, viewHolder);

    viewHolder.itemView.setAlpha(ALPHA_FULL);

    if (viewHolder instanceof ItemTouchHelperViewHolder) {
        // Tell the view holder it's time to restore the idle state
        ItemTouchHelperViewHolder itemViewHolder = (ItemTouchHelperViewHolder) viewHolder;
        itemViewHolder.onItemClear();
    }

    if (mFrom != null && mTo != null)
        mAdapter.onDrop(mFrom, mTo);

    // clear saved positions
    mFrom = mTo = null;
}
}
```

**Comment by jishuo1213** [comment]
very helpful save my life,Thank you very much

**Comment by matjazzeleznik** [comment]
@MFlisar you saved my day! Search for this kind of solution all day.. Thanks!

**Comment by Gnzlt** [comment]
Works like a charm! Thanks @MFlisar

**Comment by WasimMemon** [comment]
@MFlisar Thanks.
You saved my days of r&d...

**Comment by priyankpandya1989** [comment]
what should be the code inside onDrop ?

**Comment by AmitGunjan** [comment]
thanks, working for me
