### ISSUE TITLE
You can set the minAPI to 7

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [iPaulPro/Android-ItemTouchHelper-Demo#2]
RecyclerView allows it, including the class you use.
Only the special Alpha functions require API 13 and above.

**Comment by iPaulPro** [comment]
ItemTouchHelper `onDraw` and `onDrawOver` have different implementations on pre-Honeycomb, so in the interest of clarity, I will be keeping the min API above Honeycomb. I will, however, look into lowering the min to 15 **if** the next [Platform Versions Report](https://developer.android.com/about/dashboards/index.html) shows it maintaining over 5%.

**Comment by AndroidDeveloperLB** [comment]
But I've tested it, and it seems to still work fine on the emulator with GB.
What's the disadvantage?
You could even use the nine-old-androids for the alpha.

**Comment by iPaulPro** [comment]
I will be continuing the series to take over drawing control (overriding `onDraw`), so I don't want to add to the complexity of supporting two methods of drawing.

**Comment by AndroidDeveloperLB** [comment]
I didn't touch anything that's related to onDraw. I only disabled the parts of using the alpha.
It worked fine.
What exactly don't you like there?

**Comment by iPaulPro** [comment]
**In the future** I will be expanding on this example. It will include more control over `onDraw`. Since `ItemTouchHelper` uses different implementations for `onDraw` before Honeycomb, I will not be supporting anything before it.

I cannot explain this anymore clearly.
