### ISSUE TITLE
disable dragging for some cells

### ISSUE THREAD

**Issue by pixelbendr** [iPaulPro/Android-ItemTouchHelper-Demo#4]
Hello Paul,

so in my app I want users to be able to delete cells that they created. so for example in a group chat you can only delete a message you create. so swipe to dismiss should be disabled for messages which the user didn't create. 

Whats the best way to approach this?

**Comment by Shusshu** [comment]
In "SimpleItemTouchHelperCallback" you can return false in the "isLongPressDragEnabled" method

**Comment by iPaulPro** [comment]
Sorry @pixelbendr, I seem to have missed the notification for this issue. 

You'll notice that `getMovementFlags` provides a `RecyclerView.ViewHolder` parameter. This means that it's called for every item in the `Adapter`, individually. If you want to disable movement for a specific item, you would return `0` for that `ViewHolder`. Eg.

```
@Override
public int getMovementFlags(RecyclerView recyclerView, RecyclerView.ViewHolder viewHolder) {
    final int dragFlags = ItemTouchHelper.UP | ItemTouchHelper.DOWN;
    final int swipeFlags = ItemTouchHelper.START | ItemTouchHelper.END;
    return viewHolder.getItemViewType() == YourAdapter.Type.HEADER ? 0 : makeMovementFlags(dragFlags, swipeFlags);
}
```

**Comment by iPaulPro** [comment]
Note: You'll also have to add a type check in `onMove`. Eg

```
@Override
public boolean onMove(RecyclerView recyclerView, RecyclerView.ViewHolder source, RecyclerView.ViewHolder target) {
    // Restrict movement to source view type
    if (source.getItemViewType() != target.getItemViewType()) {
        return false;
    }

    // ...
}
```

**Comment by pixelbendr** [comment]
Hello Paul,

The items I want to disable drag on have the same view type but different userId's, if you get what I mean. 
in bind view I cast .get(i) to my model so I can do specifics. Am confused at how to get the userId's in the getMovementFlag method.
