### ISSUE TITLE
How can we save the new list after drag?

### ISSUE THREAD

**Issue by AtulaGuleria** [iPaulPro/Android-ItemTouchHelper-Demo#46]

**Comment by MrLepage** [comment]
In `onItemMove`, you have to swap your list item.

After swapping, you have access to the new list.

`@Override
public boolean onItemMove(int fromPosition, int toPosition) {
    Collections.swap(yourList, fromPosition, toPosition);
    notifyItemMoved(fromPosition, toPosition);
    return true;
}`

**Comment by AtulaGuleria** [comment]
thanks.
