### ISSUE TITLE
ItemTouchHelper can not move Horizental when using recyclerVIew as a gridview

### ISSUE THREAD

**Issue by huxq17** [iPaulPro/Android-ItemTouchHelper-Demo#5]
or some methods should be invoked in ItemTouchHelper?Can you understand what I'm saying? i have little confidence in my english.

**Comment by iPaulPro** [comment]
You have to change the `dragFlags` in `SimpleItemTouchHelperCallback`:

```
int dragFlags = ItemTouchHelper.UP | ItemTouchHelper.DOWN | 
        ItemTouchHelper.LEFT | ItemTouchHelper.RIGHT;
```

Video: https://vid.me/rEUM

**Comment by huxq17** [comment]
So cool ! thank you so much !
