### ISSUE TITLE
No shadow drawn on API>=21

### ISSUE THREAD

**Issue by almozavr** [iPaulPro/Android-ItemTouchHelper-Demo#6]
This is strange, but no shadow drawn on Lollipop, even being elevated (see `ItemTouchUIUtilImpl`), it has no effect.

**Comment by almozavr** [comment]
Created [android issue](https://code.google.com/p/android/issues/detail?id=179768&thanks=179768&ts=1436862567).

**Comment by iPaulPro** [comment]
Views must have a background for elevation shadows to show. Here's how you can do it by editing this project at b6d2464.

Add background to root view for item in `item_main.xml`:

```
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/item"
    android:layout_width="match_parent"
    android:layout_height="?listPreferredItemHeight"
    android:background="@android:color/white" >
```

Then remove the background setting in `ItemTouchHelperViewHolder` callbacks (or simply don't use it) in `RecyclerListAdapter` (130, 135):

```
    @Override
    public void onItemSelected() {
        // itemView.setBackgroundColor(Color.LTGRAY);
    }

    @Override
    public void onItemClear() {
        // itemView.setBackgroundColor(0);
    }
```

**Comment by almozavr** [comment]
@iPaulPro thanks, you're right. I'm confused that re-setting background disallows elevation shadow drawing and can't remember android-docs for this :(
