### ISSUE TITLE
Breaks with different viewTypes

### ISSUE THREAD

**Issue by scriptacus** [iPaulPro/Android-ItemTouchHelper-Demo#7]
Unfortunately, I've been unable to make this work with multiple viewTypes.  It appears that the RecyclerView scraps differing viewTypes when they are dragged over each other, which cancels the re-ordering process.  Any ideas on how to fix this?

**Comment by iPaulPro** [comment]
View type is available from the `ViewHolder`, by using the helper methods in the `LayoutManager`, or even `RecyclerView` itself (`findViewHolderForAdapterPosition`). You haven't actually explained what/where the specific issue you're having is, so it's difficult to advise. Are you testing this project at `master`? Have you made any changes? 

`SimpleItemTouchHelperCallback` at `master` is already checking for the view type, and preventing the drag over unlike types:

```
@Override
public boolean onMove(RecyclerView recyclerView, RecyclerView.ViewHolder source, RecyclerView.ViewHolder target) {
    if (source.getItemViewType() != target.getItemViewType()) {
        return false;
    }
    // ...
}
```

Simply adding something like this to `RecyclerListAdapter` works fine in my testing:

```
@Override
public int getItemViewType(int position) {
    return position < 3 ? 0 : 1;
}
```

The next part of this article series will deal with view type more, but it should be working fine, already. I'll need specific information, and likely code snippets, to help you any further.

**Comment by scriptacus** [comment]
Sorry for the lack of information.  If getItemViewType() returns two different types of items (A and B for example), then obviously onMove won't allow them to swap.  So as a test I commented out the block of code that you pasted above.  In the case of a view with 3 items (A, B, B), I can drag items UP without issue, (e.g. ending up with B, A, B by dragging one of the B items to the top of the list), but if I try to drag a non-matching item DOWN the item being dragged gets detached during onMove somewhere in the RecyclerView code, which cancels the drag operation.

That said, I found the issue.  I had based my implementation on your inital commit (the one that matches the tutorial, but then updated it to match the latest version.  During that process I missed the fact that onItemMove changed to using Collections.swap().  The previous method of swapping is what was causing the issue.

**Comment by SUPERCILEX** [comment]
@iPaulPro @scriptacus is there a way to support dragging and dropping an item across multiple view types without the drag being cancelled?

**Comment by kokilaw** [comment]
@SUPERCILEX did you find a way to do drag and drop across multiple view types?

**Comment by SUPERCILEX** [comment]
@kokilayaa I don't remember what fixed it for me, but just remember to return true in `onMove` and notify the adapter of your move in that method.
